### ISSUE TITLE
lodash seems to be a runtime dependency

### ISSUE THREAD

**Issue by steffenweber** [davidtheclark/list-selectors#1]
`lodash` is listed in `devDependencies` but seems to be a runtime dependency.

```
$ ./node_modules/.bin/list-selectors 

module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (node_modules/list-selectors/index.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Of course, this be easily fixed manually by running `npm install lodash`.

**Comment by davidtheclark** [comment]
Thanks for pointing that out. I must have changed things while developing and forgotten to change `package.json`. Fixed in v0.1.1
